[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aoc_tools"
version = "0.0.0"
description = "Lovely Spam! Wonderful Spam!"
readme = "README.rst"

