name: Test workflow

on:
  push:
    branches: [main]

jobs:
  echo_stuff:
    runs-on: ubuntu-latest
    steps:
      - name: hello world job
        run: echo ${{ github.event.head_commit.message }}
